### ISSUE TITLE
Who is this for?

### ISSUE THREAD

**Issue by jdbann** [jdbann/table#13]
I'm realising now that a lot of my decisions and preferences have been based on an assumption that this was just to make it easier for me to run our Dragon of Icespire Peak campaign. I take it you want to get this working well enough to use in other campaigns @cpytel?

If that's the case, is it worth doing some interviews?

I started building this to see what Rails' approach to js can do, and started working on features to support my own needs. Then I think I got a bit defensive or protective. I'd rather have a clearer picture of who we're trying to build this for so that I can strike a better balance.

**Comment by cpytel** [comment]
I don't think you've been defensive or protective - From my perspective, it's felt like our goals have been the same: to create something simple to use.

I think if we do that well it _will_ be useful to other folks. I don't think we need to interviews because we are primarily building something for ourselves and our assumptions right now, and the best way to validate those assumptions based on where we're at is putting the software in the hands of real users.

I do believe there is an opportunity to make something useful to people. Right now nearly every D&D group in the world is going through the same experience as us of moving their campaign online if they want to keep playing.

**Comment by cpytel** [comment]
Bringing two things over from #12 which are more relevant here.

> I just didn't want to get caught up in extra associations and permissions

My goal would be to introduce the minimal amount of new models and associations to know who should be able to access a campaign and who the dm and players are. 

> should it be a single hosted instance or should a party start their own up?

The other people who I'm playing with who would use this would not be comfortable setting up their own instance.

**Comment by jdbann** [comment]
> I don't think you've been defensive or protective

That's good to hear. Bored as I was in isolation, I still probably shouldn't have been triaging issues when I was feeling pretty weak.

> My goal would be to introduce the minimal amount of new models and associations to know who should be able to access a campaign and who the dm and players are.

I wasn't expecting anything excessive, I was just hoping to avoid that whole layer. But it looks like we'll be hosting it for numerous groups so we've got to put something in. Right now I don't see a need to require players to register for accounts, could we keep them public for now?

**Comment by jdbann** [comment]
I think we have a clearer sense now 👍
