### ISSUE TITLE
UI for creating tokens

### ISSUE THREAD

**Issue by jdbann** [jdbann/table#27]
Some form of UI for creating new tokens. Ideally within the campaign page so they can be created without leaving the map view

**Comment by cpytel** [comment]
I’ve got this started in the create-tokens branch. I’ve got a basic UI for creating tokens in place, but I need to add publishing (and consuming) of actioncable events so that other people see them added to the map.

I will hopefully be able to wrap it up today, but it likely won’t be until late afternoon or evening my time.

**Comment by cpytel** [comment]
Since we’re not playing this week anymore, I sort of ran out of time on this and decided to hang out with family.
