### ISSUE TITLE
Build tokens from token templates

### ISSUE THREAD

**Issue by jdbann** [jdbann/table#29]
The same tokens will be needed across multiple maps (eg players), and multiple instances of some tokens will be needed on the same map (eg monsters). Having a template for a token would help us avoid needing to upload the same photos countless times and enter details again.

Ideally a campaign would have player token templates which can be automatically added to a map en-masse.

**Comment by cpytel** [comment]
Do you think it could make sense to introduce either a `Player` or `Character` model that stores the info needed for their token?

**Comment by jdbann** [comment]
Yeah, it's probably appropriate. I imagine we'd end up having a `Character` editable by a player.

I was thinking it might be helpful to also have a `CharacterToken` model, but it could inherit from `Token` and we can set the token table up for STI.

**Comment by cpytel** [comment]
If the goal is to make it so players don’t need to log into user accounts, we need to be a little careful about how we do that, otherwise we may end up jumping through hoops to associate the people active on the page with a specific player, when it could more simply be solved by having them log in to a User.

**Comment by jdbann** [comment]
Ah yes, player editing would be a later goal and we'd probably have the option for players to register by then.

**Comment by cpytel** [comment]
I started on this in #43.

Now that I've started on it, I think that rather than a token template, it might make sense to add the first token of a certain type. For example, add a token for an orc with #27, and then rather than using a template as you originally envisioned, you could duplicate the token, which would copy its name, adding an incrementing integer to it, and copying its image.

Let me know what you think about that.

**Comment by jdbann** [comment]
That could work! I was just thinking that something like a template would allow you to update a character or monster's image across all tokens, and that you could associate character templates to a campaign to easily add all the character tokens to a new map.

**Comment by jdbann** [comment]
The templates would be more about duplicating tokens across maps or even campaigns. It would be great to have a quick method for duplicating tokens as you outlined above in an individual map though.

**Comment by cpytel** [comment]
Ok, I see what you're going for. I think my preference rather than having TokenTemplate and STI is to have a go at creating specific models for things that can have tokens: Characters, Monsters, etc. That way they can have different behavior. For example, we want all characters in a campaign to automatically receive a token on maps in the campaign, but not monsters. Monsters are more like a "library" that you pull from to make tokens.

This method still allows you to update the image or name across all tokens, and gives us explicit Types can have custom behavior.

See where I'm going?

**Comment by jdbann** [comment]
I think we're pretty much talking about the same thing. My 'templates' would be the equivalent of your `Tokenable` association.

Inheritance would still allow us to have different logic for different types of token, but hold a single definition of what is required to create a token based on a template.

However we do it, it seems like we're trying to achieve the same thing so sounds good 👍
