### ISSUE TITLE
Dragging tokens in Firefox leaves them in weird locations 

### ISSUE THREAD

**Issue by jdbann** [jdbann/table#54]
Thanks Tom 🙄

**Comment by cpytel** [comment]
Oh boy, so I've done some research on this today and it's not too pretty. It turns out that `clientX` and `clientY` are always set to 0 in Firefox on the drag event. This is a bug in Firefox that has been open for 11 years (https://bugzilla.mozilla.org/show_bug.cgi?id=505521) and is full of people talking past each other, and pedantic arguments about why it shouldn't work that way.

It looks like the [workaround](https://bugzilla.mozilla.org/show_bug.cgi?id=505521#c8) is to set a `dragover` event on the document which allows you to capture the mouse coordinates.

**Comment by cpytel** [comment]
Apprently firefox does set `screenX` and `screenY` on `dragend` event, so another workaround might be to not have firefox show full token movement, and only have it move the token to the final destination. However, we'd then be sure not to send the `clientX` and `clientY` of `0`.

**Comment by jdbann** [comment]
> another workaround might be to not have firefox show full token movement, and only have it move the token to the final destination

To me the full movement is important. Being able to nudge the token or show a path gives a lot of expression.

**Comment by cpytel** [comment]
Agreed, I've opened up #58 with a WIP fix with the workaround of watching `dragover` on the map.

**Comment by cpytel** [comment]
Fwiw, It's also possible that other DM functionality using drag and drop is also broken, I haven't checked yet.

**Comment by jdbann** [comment]
Eugh. It does look like a pretty grim state of affairs. Drag and drop definitely seems designed for discrete movements ie going from one container to another.

Perhaps we have to go back to mouse events? Drag and drop meant not having to implement drop areas. If this problem looks too messy then maybe we take that approach and have more control over the full behaviour?

**Comment by cpytel** [comment]
Hard to say at this point whether it’s just this one workaround and worth it, or the start of multiple workarounds for Firefox and it makes sense to go back to mouse events.

My plan is to do some more testing to see if there are other problems, see what the deal is with the specs, and then see if what might make the most sense long term. Sound ok?

**Comment by jdbann** [comment]
> My plan is to do some more testing to see if there are other problems, see what the deal is with the specs, and then see if what might make the most sense long term. Sound ok?

Yeah, I'd be interested to hear your findings. I can explain what's happening with the specs a bit more of that'd help

**Comment by cpytel** [comment]
Ok, there are no other problems on the player or DM side that I can see with Firefox that aren't fixed with this workaround.

The reason why the specs fail is that we're manually firing all the drag events in the specs, so we weren't manually triggering `dragover` previously because we didn't need to.

I've pushed up a fix to the specs and also fixed the problem because pointTo was using the same mapPosition function in #58

**Comment by jdbann** [comment]
Great! I'll keep implementation discussion on #58
